server {
    listen 80;
    listen [::]:80;

    server_name region-one.pi.lan;

    set $note_upstream note-service:8080;
    set $todo_upstream todo-service:8080;

    location /config/frontend {
        alias /usr/share/nginx/config/frontend/dev/;
        autoindex off;
        default_type application/json;
    }

    location /config/services {
        alias /usr/share/nginx/config/services/;
        autoindex off;
        default_type application/json;
        allow 172.18.0.0/16;
        deny all;
    }

    location /todo-client {
        alias /usr/share/nginx/html/todo-client/current/;
        add_header Access-Control-Allow-Origin "*";
        autoindex off;
    }

    location /note-client {
        alias /usr/share/nginx/html/note-client/current/;
        add_header Access-Control-Allow-Origin "*";
        autoindex off;
    }

    location / {
        root /usr/share/nginx/html/shell/current/;
        try_files $uri $uri/ /index.html;
    }

    include conf.d/backend/services.conf;
}
