server {
    listen 80;
    listen [::]:80;

    server_name region-one.pi.lan;

    set $note_upstream note-service:8080;
    set $todo_upstream todo-service:8080;

    location /config/frontend {
        alias /usr/share/nginx/config/frontend/;
        autoindex off;
        default_type application/json;
    }

    location /config/services {
        alias /usr/share/nginx/config/services/;
        autoindex off;
        default_type application/json;
        deny 172.18.0.0/16;
        allow all;
    }

    location /todo-client/ {
        root /usr/share/nginx/html/todo-client/;
        try_files $uri $uri/;
    }

    location /note-client/ {
        root /usr/share/nginx/html/note-client/;
        try_files $uri $uri/;
    }

    location / {
        root /usr/share/nginx/html/shell/;
        try_files $uri $uri/ /index.html;
    }

    include conf.d/backend/services.conf;
}
