server {
    listen 80;
    listen [::]:80;

    server_name region-one.pi.lan;

    location /todo-client/ {
        root /usr/share/nginx/html/todo-client/;
        try_files $uri $uri/;
    }

    location /note-client/ {
        root /usr/share/nginx/html/note-client/;
        try_files $uri $uri/;
    }

    location / {
        root /usr/share/nginx/html/shell/;
        try_files $uri $uri/ /index.html;
    }
}
