include conf.d/maps/default.conf;

server {
    listen 80;
    listen [::]:80;

    server_name _;
    include conf.d/vars/default.conf;

    location /config/frontend {
        alias /usr/share/nginx/config/frontend/local/;
        autoindex off;
        default_type application/json;
    }

    location /config/services {
        alias /usr/share/nginx/config/services/;
        autoindex off;
        default_type application/json;
        allow 172.18.0.0/16;
        deny all;
    }

    include conf.d/backend/services.conf;

    location / {
        root /usr/share/nginx/html/shell/;
        try_files $uri $uri/ /index.html;
    }
}
