services:
  note-service:
    container_name: note-service
    extra_hosts:
      - host.docker.internal:host-gateway # Required for linux based systems not running docker desktop
    image: virabshetkar/note-service:region-one-dev
    environment:
      - ASPNETCORE_URLS=http://+:8080 # '+' is required for host binding
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_REMOTE_CONFIG=true
      - REMOTE_CONFIG_URL=http://reverse-proxy/config/services/note-service/ # Trailing slash is required
    networks:
      - local-network

networks:
  local-network:
    external: true