resolver 127.0.0.11;

map $note_env $notes_upstream {
    "dev"     pi.lan;
    "local"   note-service:8080;
    default   pi.lan;
}

map $todo_env $todo_upstream {
    "dev"     pi.lan;
    "local"   todo-service:8080;
    default   pi.lan;
}

