name: CD Server

run-name: ${{inputs.repo}} -- ${{inputs.commitId}}

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Repo to deploy
        options:
          - todo-service
          - note-service
      commitId:
        type: string
        description: Commit Id in the repo to deploy

jobs:
  deploy:
    uses: virabshetkar-org/pipeline-templates/.github/workflows/server-deploy.yml@main
    with:
      repo: ${{ inputs.repo }}
      commitId: ${{ inputs.commitId }}
