name: CD Server

run-name: ${{inputs.repo}} -- ${{inputs.commitId}}

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Repo to deploy
        options:
          - todo-service
          - note-service
      commitId:
        type: string
        description: Commit Id in the repo to deploy

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    steps:
      - name: Tag commit id
        run: docker buildx imagetools create --tag virabshetkar/${{inputs.repo}}:region-one-dev virabshetkar/${{inputs.repo}}:${{inputs.commitId}} 
      - name: Checkout Branch
        uses: actions/checkout@v6
        with:
          path: configuration
      - name: Restart Container
        working-directory: configuration/docker/${{inputs.repo}}
        run: | 
          docker compose pull
          docker compose up
