name: CD Server

run-name: ${{inputs.repo}} -- ${{inputs.commitId}}

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Repo to deploy
        options:
          - virabshetkar/todo-service
          - virabshetkar/note-service
      commitId:
        type: string
        description: Commit Id in the repo to deploy

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    steps:
      - name: Tag commit id
        run: docker buildx imagetools --tag ${{inputs.repo}}:region-one-dev ${{inputs.repo}}:${{inputs.commitId}} 
