name: CICD (Client)

run-name: ${{inputs.repo}}:${{inputs.commitId}} Build & Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Repository Location
        options:
          - virabshetkar-org/application.note
          - virabshetkar-org/application.todo
          - virabshetkar-org/reverse-proxy
      commitId:
        type: string
        description: Commit ID of the repo
        
jobs:
  ci-cd:
    uses: virabshetkar-org/pipeline-templates/.github/workflows/client-ci-cd.yml@main
    with:
      repo: ${{ inputs.repo }}
      commitId: ${{ inputs.commitId }}
